### ISSUE TITLE
Dest mac address from ethernet connected computer.

### ISSUE THREAD

**Issue by Mas313** [escitalopram/wlan_kabel#10]
Hi,
I want to know that  when issuing the commad
`./wlan_kabel wlan-adapter ethernet-adapter MAC of device to connect`

1. wha is the paramter `MAC of device to connect` . Is it a computer with no WLAN
2. what about the sate of WLAN device on proxy? would it be connected to router with internet?. If it is connected to internet than how we can prevent it to not have an IP address as mentioned in Readme section. 
3. Should we use DHCP on computer without WLAN or on both systems including proxy.  In the Readme section its mentioned that no IP should be assigned to proxy ethernet interface, then how data would flow to and from proxy ethernet to connected computer without any IP assigned.
Thanks

**Comment by escitalopram** [comment]
Hi…

1. This is the hardware address of the network adapter, it looks something like `02:42:11:36:73:bc` On Linux, you can find it using `ip link`; it is the address shown between `link/ether` and `brd`. Other OSes should allow you to find the MAC, too, but I don't know how.
2. The proxy device is meant to directly pass packets between its Ethernet and WLAN devices, therefore normal operation with routing is not possible, because the proxy would have a hard time differentiating between packets intended for itself and ones that should be passed on.  If the device only has one WLAN interface and one ethernet adapter, accessing the internet with the proxy device is not possible. However, WLAN_kabel cannot select which WLAN AP to use, therefore you must connect it first e.g. via wpa_supplicant.
3. As mentioned above, neither of the two network adapters on the proxy can be used for anything else while WLAN_kabel is active. Therefore DHCP can't be used by the proxy on neither interface. Instead, DHCP requests of the computer without WLAN will be directly passed on to the AP (just like with an Ethernet cable, but the other end is connected wirelessly to a WLAN AP). To make this possible, WLAN_kabel works on a layer below TCP/IP, on the data link layer of the OSI layer model.

**Comment by Mas313** [comment]
Thanks
