### ISSUE TITLE
Pi Configuration

### ISSUE THREAD

**Issue by abewieland** [escitalopram/wlan_kabel#3]
In the readme, you stated wlan_kabel had been tested on a Raspberry Pi. I have tried extensively to operate it on a Pi, to no avail. Could you provide the testing configuration that succeeded? (/etc/network/interfaces, what other networking daemons or tools were installed) Thanks.

**Comment by escitalopram** [comment]
It has been a while since I last ran it on the Pi; probably a lot of its OS has changed meanwhile, and I don't have one within reach at the moment.

AFAIR, what I did was to make sure the OS doesn't touch the network interfaces (no network manager or similar services, no dhcpcd or similar).

For the Wireless I manually started wpa_supplicant.
Then, I made sure both network adapters were up (something like `ip link set dev eth0 up` and also for the Wireless)
If there are any IP addresses configured on the interfaces you wish to use (`ip addr`), remove them. I'm not sure about the IPv6 addresses; if they break anything, disable IPv6 via sysctl.

At this point, the interfaces should be ready to start wlan_kabel.

If it works, you can make a script to automate above steps.

If it still doesn't work, please describe what kind of problem you're running into (error messages, etc.)

**Comment by escitalopram** [comment]
Ok, my bad, It wasn't me who tested the PI, it was some contributor. But the description should be generic enough to work with the Pi, too.

**Comment by abewieland** [comment]
After extensive testing, I found I can connect to the network with a static IP, but not with DHCP. With a static IP, the connected device is able to access the local network, but it can't access anything past that. Is there something stopping DHCP? The Pi's /etc/network/interfaces file:

```
# interfaces(5) file used by ifup(8) and ifdown(8)
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet manual

auto wlan0
iface wlan0 inet manual
   wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf
```
On the Pi, IPv6 is disabled in /etc/modprobe.d/ipv6.conf:

```
# Don't load ipv6 by default
alias net-pf-10 off
alias ipv6 off

blacklist ipv6
```
I get no error messages from either machine. The computer behind simply refuses to connect through DHCP.

**Comment by abewieland** [comment]
I retract my statement about the internet issue. I had foolishly not specified my nameservers with my static IP. So, the product works for me in everything but DHCP. That's good enough for me. Thanks!
