### ISSUE TITLE
Workaround: Use VPN for reaching multiple VMs?

### ISSUE THREAD

**Issue by Lalarian** [escitalopram/wlan_kabel#5]
Hello!

I have been struggling with multiple different stubborn WiFi adapters for years now, which just won't bridge (Operation not supported). So I am always searching for alternatives, to make my VMs arbitrarily reach the internet and vice versa and appear in my LAN as bridged hosts.
wlan_kabels says to only work for a single client.
But: What if I run an VPN (like Tinc) from my router to one VM behind wlan_kabel, so the VPN acts as a bridge to the other VMs?
(I am thinking of a configuration like [this](https://www.digitalocean.com/community/tutorials/how-to-install-tinc-and-set-up-a-basic-vpn-on-ubuntu-14-04), where **ams1 would be the router**, **externalnyc would be the VM connected by wlan_kabe**l, and **internalnyc is another VM**, just reachable through the VPN.)
Wouldn't this make the other client's in the VM's network reachable for broadcasts through the VPN, with a suitable Tinc-configuration? 
And would it make fresh created VMs reachable without having to create annoying firewall rules and routes?
This network configuration is beyond my understanding, I am only assuming, that there might be a chance..

Thank you! :)

**Comment by escitalopram** [comment]
Im not really familiar with tinc, but I see no problem reaching multiple hosts through a VPN tunnel over wlan_kabel. Just be careful to configure the MTU at the non-WLAN interface so that it is small enough to also work with the WLAN interface (which has typically a smaller MTU than Ethernet, iirc). Regarding broadcast I think that it should work if tinc supports it, and if you access both VMs through the VPN

**Comment by Lalarian** [comment]
Thank you, I will try this now, maybe I will need some help with network configuration. Will take me some days anyways and then we'll see.. :)
